spring:
    application:
        name: backend-api
    output:
        ansi:
            enabled: always

springdoc:
    swagger-ui:
        path: /swagger-ui
    api-docs:
        path: /api/v1/api-docs

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.web: TRACE