services:
# Application containers
    backend-api:
        build:
            context: .
            dockerfile: Dockerfile
        image: booking-service/backend-api:latest
        container_name: backend-api
        env_file: .env
        environment:
            SPRING_PROFILES_ACTIVE: dev
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        ports:
            - 8080:8080
        networks:
            - app-network
        volumes:
            - logs:/var/log/app
# Reverse-proxy Nginx + SSL
    nginx:
        image: nginx:1.27.2
        container_name: nginx
        restart: always
        depends_on:
            backend-api:
                condition: service_started
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/dev:/etc/nginx/conf.d
            - ./certs:/etc/mycerts
        networks:
            - app-network

volumes:
    logs:
        name: logs
        driver: local

networks:
    app-network:
        name: app-network
        driver: bridge
