spring:
    profiles:
        active: debug
    application:
        name: backend-api
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    jpa:
        open-in-view: false

springdoc:
    swagger-ui:
        path: /swagger-ui
    api-docs:
        path: /api/v1/api-docs

server:
    port: 8080