spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgres:5432/main_db
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
    jpa:
        hibernate:
            ddl-auto: validate
    liquibase:
        enabled: true
        drop-first: false
        change-log: classpath:db/changelog/master.xml
        default-schema: public

logging:
    config: classpath:log4j2-stage.xml
    level:
        com.bookingapp: WARN
        org.springframework.security: WARN
        org.springframework.web: WARN

minio:
    url: http://minio:9000
    access-key: ${MINIO_USER}
    secret-key: ${MINIO_PASS}
    bucket-name: default