spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/main_db
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASS}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    liquibase:
        enabled: false

logging:
    config: classpath:log4j2-dev.xml
    level:
        com.bookingapp: DEBUG
        org.springframework.security: TRACE
        org.springframework.web: TRACE